apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-with-config-map-service
  labels:
    app: with-config-map
spec:
  type: 'LoadBalancer'
  ports:
    - protocol: TCP
      name: 'http'
      port: 3000
      targetPort: 3000
  selector:
    app: with-config-map