apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-docker-env-with-secret-deployment
  labels:
    app: with-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: with-secret
  template:
    metadata:
      labels:
        app: with-secret
    spec:
      containers:
        - image: marcelmichau/express-docker-env:latest
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 3000
          env:
            - name: MY_AWESOME_VARIABLE
              valueFrom:
                secretKeyRef:
                  name: my-awesome-secret
                  key: awesomeEnvironmentVariable
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
