apiVersion: v1
kind: Service
metadata:
  name: express-docker-env-with-secret-service
  labels:
    app: with-secret
spec:
  type: 'LoadBalancer'
  ports:
    - protocol: TCP
      name: 'http'
      port: 3001
      targetPort: 3000
  selector:
    app: with-secret