apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-with-config-map-deployment
  labels:
    app: with-config-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: with-config-map
  template:
    metadata:
      labels:
        app: with-config-map
    spec:
      containers:
        - image: marcelmichau/express-docker-env:latest
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-my-awesome-config-map
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
